In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import math

from torch import optim
from tqdm import tqdm

In [13]:
xs = torch.tensor([[0.,0.],[1.,0.],[0.,1.],[1.,1.]])

# and
# ys = torch.tensor([[0],[0],[0],[1]]).float()
# nand
# ys = torch.tensor([[1],[1],[1],[0]]).float()
# xor
# ys = torch.tensor([[0],[1],[1],[0]]).float()
# or
# ys = torch.tensor([[0],[1],[1],[1]]).float()
# nor
# ys = torch.tensor([[1],[0],[0],[0]]).float()
# ~xor
ys = torch.tensor([[1],[0],[0],[1]]).float()

In [14]:
model = nn.Sequential(nn.Linear(2, 16), nn.ReLU(), nn.Linear(16, 1), nn.Sigmoid())

In [15]:
EPOCHS = 5_000
opt = optim.Adam(model.parameters(), lr=1e-3)
lossf = nn.BCELoss()

for _ in tqdm(range(EPOCHS)):
    opt.zero_grad()
    loss = lossf(model(xs), ys)
    
    print(f"{loss.item()=}")

    loss.backward()
    opt.step()

 27%|██▋       | 1349/5000 [00:00<00:00, 7004.42it/s]

loss.item()=0.6991263628005981
loss.item()=0.6985024213790894
loss.item()=0.6978816390037537
loss.item()=0.6972636580467224
loss.item()=0.6966489553451538
loss.item()=0.6960383653640747
loss.item()=0.6954378485679626
loss.item()=0.6948390007019043
loss.item()=0.6942422389984131
loss.item()=0.693648099899292
loss.item()=0.6930567026138306
loss.item()=0.692469596862793
loss.item()=0.6918879747390747
loss.item()=0.6913089156150818
loss.item()=0.690732479095459
loss.item()=0.6901586055755615
loss.item()=0.689591646194458
loss.item()=0.6890266537666321
loss.item()=0.688463568687439
loss.item()=0.6879023313522339
loss.item()=0.6873549818992615
loss.item()=0.6868827939033508
loss.item()=0.6864116787910461
loss.item()=0.6859413385391235
loss.item()=0.6854714751243591
loss.item()=0.6850023865699768
loss.item()=0.6845343112945557
loss.item()=0.684070348739624
loss.item()=0.6836060285568237
loss.item()=0.683142364025116
loss.item()=0.682680606842041
loss.item()=0.6822194457054138
loss.item()=0.68

 59%|█████▉    | 2962/5000 [00:00<00:00, 7724.79it/s]

loss.item()=0.06248268485069275
loss.item()=0.062362734228372574
loss.item()=0.06225264444947243
loss.item()=0.062136635184288025
loss.item()=0.06201548129320145
loss.item()=0.06190585717558861
loss.item()=0.0617908276617527
loss.item()=0.06166904419660568
loss.item()=0.061561137437820435
loss.item()=0.06144777685403824
loss.item()=0.061331652104854584
loss.item()=0.061223700642585754
loss.item()=0.06110997498035431
loss.item()=0.06099393963813782
loss.item()=0.060877785086631775
loss.item()=0.06076445430517197
loss.item()=0.06065453961491585
loss.item()=0.06054404377937317
loss.item()=0.06044045835733414
loss.item()=0.060324378311634064
loss.item()=0.06020861119031906
loss.item()=0.060103584080934525
loss.item()=0.059996142983436584
loss.item()=0.059888679534196854
loss.item()=0.05977116525173187
loss.item()=0.05966338515281677
loss.item()=0.059556011110544205
loss.item()=0.05945323407649994
loss.item()=0.059344202280044556
loss.item()=0.059234123677015305
loss.item()=0.05912773683667

 92%|█████████▏| 4624/5000 [00:00<00:00, 8071.38it/s]

loss.item()=0.007668259087949991
loss.item()=0.007661072537302971
loss.item()=0.007653901353478432
loss.item()=0.007646538317203522
loss.item()=0.0076391869224607944
loss.item()=0.007631517481058836
loss.item()=0.007624165620654821
loss.item()=0.007616465911269188
loss.item()=0.007609817199409008
loss.item()=0.00760264415293932
loss.item()=0.007595199625939131
loss.item()=0.007587818428874016
loss.item()=0.007580542005598545
loss.item()=0.0075732506811618805
loss.item()=0.007566030602902174
loss.item()=0.007558751851320267
loss.item()=0.007551460061222315
loss.item()=0.007544318679720163
loss.item()=0.007536862976849079
loss.item()=0.0075296927243471146
loss.item()=0.007522763684391975
loss.item()=0.007514975965023041
loss.item()=0.007507905829697847
loss.item()=0.007501095067709684
loss.item()=0.007494242396205664
loss.item()=0.007486953400075436
loss.item()=0.0074793933890759945
loss.item()=0.007472432218492031
loss.item()=0.0074654556810855865
loss.item()=0.007458239793777466
loss.i

100%|██████████| 5000/5000 [00:00<00:00, 7729.68it/s]

loss.item()=0.0019479109905660152
loss.item()=0.001946462201885879
loss.item()=0.0019450285471975803
loss.item()=0.0019435948925092816
loss.item()=0.0019422061741352081
loss.item()=0.0019408917287364602
loss.item()=0.0019395026611164212
loss.item()=0.001938053872436285
loss.item()=0.001936530228704214
loss.item()=0.0019351709634065628
loss.item()=0.0019338864367455244
loss.item()=0.001932467450387776
loss.item()=0.0019310485804453492
loss.item()=0.0019296301761642098
loss.item()=0.0019282563589513302
loss.item()=0.0019269270123913884
loss.item()=0.0019255081424489617
loss.item()=0.0019240444526076317
loss.item()=0.0019225655123591423
loss.item()=0.0019213855266571045
loss.item()=0.0019200264941900969
loss.item()=0.001918607740662992
loss.item()=0.0019171589519828558
loss.item()=0.0019157250644639134
loss.item()=0.0019144259858876467
loss.item()=0.0019130967557430267
loss.item()=0.0019117079209536314
loss.item()=0.0019102438818663359
loss.item()=0.001908899750560522
loss.item()=0.001907

In [16]:
model[0].weight

Parameter containing:
tensor([[-0.2061, -0.6291],
        [ 1.8196, -1.1551],
        [ 1.6952, -1.6953],
        [ 1.4377, -1.4378],
        [ 1.5960, -1.5961],
        [-2.2168,  2.2289],
        [ 1.4864, -1.4865],
        [-1.4651, -1.4651],
        [ 1.4895, -1.4895],
        [ 1.5930, -1.5930],
        [ 0.1618,  0.2355],
        [ 0.1324, -0.5435],
        [ 0.3651, -0.1080],
        [-0.1618, -0.0906],
        [ 2.0962, -1.0398],
        [-0.4243, -0.0537]], requires_grad=True)

In [17]:
model[0].bias

Parameter containing:
tensor([-4.3809e-01,  1.1551e+00, -4.9807e-06,  4.2190e-05,  1.0141e-05,
         1.0073e-04, -1.8821e-07,  1.4650e+00, -7.9458e-06,  3.0775e-05,
        -4.2764e-01, -2.1171e-01, -3.8372e-01, -5.4093e-02,  1.0399e+00,
        -6.0037e-01], requires_grad=True)

In [18]:
import itertools
out_text = ""
out_text += "# out_vec is also used as a doublebuffer\n"
out_text += "function runnet(vec, out_vec,  mat, bias)\n"
out_text += "{\n"
out_text += "\t# init variable\n"
out_text += "\tout_vec[0]=-1\n"

vec_size = None
for mod in model:
    if type(mod) is nn.Linear:
        for i, row in enumerate(mod.weight):
            for j, elem in enumerate(row):
                out_text += f"\tmat[{i},{j}]={elem.item():.5f}\n"
        
        n, m = mod.weight.shape
        vec_size = n
        out_text += f"\tmat_vec_mul(mat, vec, {n}, {m}, out_vec)\n"
        
        for i, elem in enumerate(mod.bias):
            out_text += f"\tbias[{i}]={elem.item():.5f}\n"
        
        out_text += f"\tvec_add(out_vec, bias, vec, {n})\n"
    elif type(mod) is nn.ReLU:
        out_text += f"\trelu(vec, out_vec, {vec_size})\n"
        out_text += f"\tcopy_vec(out_vec, vec, {vec_size})\n"
    elif type(mod) is nn.Sigmoid:
        out_text += f"\tsigmoid(vec, out_vec, {vec_size})\n"
        out_text += f"\tcopy_vec(out_vec, vec, {vec_size})\n"
        
out_text += "}\n"

In [19]:
print(out_text)

# out_vec is also used as a doublebuffer
function runnet(vec, out_vec,  mat, bias)
{
	# init variable
	out_vec[0]=-1
	mat[0,0]=-0.20608
	mat[0,1]=-0.62907
	mat[1,0]=1.81959
	mat[1,1]=-1.15511
	mat[2,0]=1.69524
	mat[2,1]=-1.69526
	mat[3,0]=1.43765
	mat[3,1]=-1.43777
	mat[4,0]=1.59596
	mat[4,1]=-1.59607
	mat[5,0]=-2.21684
	mat[5,1]=2.22886
	mat[6,0]=1.48645
	mat[6,1]=-1.48647
	mat[7,0]=-1.46509
	mat[7,1]=-1.46513
	mat[8,0]=1.48948
	mat[8,1]=-1.48951
	mat[9,0]=1.59300
	mat[9,1]=-1.59303
	mat[10,0]=0.16184
	mat[10,1]=0.23550
	mat[11,0]=0.13237
	mat[11,1]=-0.54353
	mat[12,0]=0.36506
	mat[12,1]=-0.10798
	mat[13,0]=-0.16183
	mat[13,1]=-0.09061
	mat[14,0]=2.09623
	mat[14,1]=-1.03984
	mat[15,0]=-0.42427
	mat[15,1]=-0.05367
	mat_vec_mul(mat, vec, 16, 2, out_vec)
	bias[0]=-0.43809
	bias[1]=1.15511
	bias[2]=-0.00000
	bias[3]=0.00004
	bias[4]=0.00001
	bias[5]=0.00010
	bias[6]=-0.00000
	bias[7]=1.46502
	bias[8]=-0.00001
	bias[9]=0.00003
	bias[10]=-0.42764
	bias[11]=-0.21171
	bias[12]=-0.38372
	bias[

In [20]:
model[0](torch.tensor([[1., 1.]]))

tensor([[-1.2732e+00,  1.8196e+00, -2.7750e-05, -7.3205e-05, -1.0442e-04,
          1.2124e-02, -1.6878e-05, -1.4652e+00, -3.8940e-05, -3.7960e-06,
         -3.0303e-02, -6.2286e-01, -1.2664e-01, -3.0654e-01,  2.0963e+00,
         -1.0783e+00]], grad_fn=<AddmmBackward0>)

In [21]:
with open("mynet.awk", "w") as f:
    f.write(out_text)